import type { Project } from './types';
import type { BaseSector } from '../types';

export const mockProjects: Project[] = [
  {
    id: 1,
    name: 'Example Project',
    items: [
      {
        id: 1,
        name: 'Page 1',
        level: 'page',
        x: 50,
        y: 50,
        width: 800,
        height: 600,
        rotation: 0,
        scale: 1,
      },
      {
        id: 2,
        name: 'Header',
        level: 'view',
        x: 50,
        y: 50,
        width: 800,
        height: 100,
        rotation: 0,
        scale: 1,
        parentId: 1,
      },
      {
        id: 3,
        name: 'Logo',
        level: 'sector',
        x: 60,
        y: 60,
        width: 80,
        height: 80,
        rotation: 0,
        scale: 1,
        parentId: 2,
      },
    ],
  },
];

export const mockItems: BaseSector[] = [
  {
    id: 1,
    x: 100,
    y: 100,
    width: 800,
    height: 600,
    rotation: 0,
    scale: 1,
    name: 'Main Page',
    level: 'page',
    projectId: 1,
  },
  {
    id: 2,
    x: 50,
    y: 50,
    width: 400,
    height: 300,
    rotation: 0,
    scale: 1,
    name: 'Header View',
    parentId: 1,
    level: 'view',
    projectId: 1,
  },
  {
    id: 3,
    x: 50,
    y: 400,
    width: 400,
    height: 150,
    rotation: 0,
    scale: 1,
    name: 'Content View',
    parentId: 1,
    level: 'view',
    projectId: 1,
  },
];
